<!-- 초기화 -->
drop table customer 
drop table ACCOUNT 
drop table ACCOUNTLOG 

delete from account

<!-- 테이블 생성  -->
CREATE TABLE CUSTOMER(
CUSTID VARCHAR2(20) PRIMARY KEY, 
PASSWORD VARCHAR2(20) NOT NULL,
EMAIL VARCHAR2(30) NOT NULL,
DIVISION VARCHAR2(20) NOT NULL,
NAME VARCHAR2(30) NOT NULL,
IDNO VARCHAR2(20) UNIQUE,
ADDRESS VARCHAR2(100)
);

delete from ACCOUNT;
delete from ACCOUNTLOG;




CREATE TABLE ACCOUNT(
ACCOUNTNO VARCHAR2(20) PRIMARY KEY,
CUSTID VARCHAR2(20),
ACCOUNTTYPE VARCHAR2(10),
BALANCE NUMBER DEFAULT 0,
PAYMENT NUMBER,
INTEREST NUMBER(3,2) DEFAULT 0,
STARTDEPOSIT DATE,
ENDDEPOSIT DATE,
APPROVAL VARCHAR2(2),
constraint PK_CUSTID FOREIGN KEY (CUSTID) REFERENCES CUSTOMER(CUSTID) ON DELETE CASCADE 
)


<!-- 제약조건 추가(test용) --> 
alter table CUSTOMER add primary key (CUSTID)
UPDATE CUSTOMER SET CUSTID = 'aaa' WHERE CUSTID  = 'aa';
alter table ACCOUNT add primary key (ACCOUNTNO)

<!-- ACCOUNTLOG 거래내역정보 테이블 , 왜 FK 인라인방식 안되었을까? -->
CREATE TABLE ACCOUNTLOG(
LOGID NUMBER PRIMARY KEY,
CUSTID VARCHAR2(20) ,
ACCOUNTNO VARCHAR2(20),
TRANSFERNO VARCHAR2(20),
EVENTDATE DATE DEFAULT SYSDATE,
EVENTTYPE VARCHAR2(10),
EVENTRECORD VARCHAR2(20),
AMOUNT NUMBER DEFAULT 0,
BALANCE NUMBER,
CONSTRAINT FK_CUSTID FOREIGN KEY (CUSTID) REFERENCES CUSTOMER(CUSTID) ON DELETE CASCADE,
CONSTRAINT FK_ACCOUNTNO FOREIGN KEY (ACCOUNTNO) REFERENCES ACCOUNT(ACCOUNTNO) ON DELETE CASCADE
);

CREATE SEQUENCE ACCOUNTLOG_SEQ start with 1 increment by 1;
CREATE SEQUENCE QNABOARD_SEQ start with 1 increment by 1;

commit

SELECT * FROM CUSTOMER

CREATE TABLE QNABOARD(
	BOARDNO NUMBER PRIMARY KEY,
	CUSTID VARCHAR(20) REFERENCES CUSTOMER(CUSTID) ON DELETE CASCADE,
	TITLE VARCHAR(20) NOT NULL, 
	CONTENT VARCHAR(4000) NOT NULL,
	REGDATE DATE DEFAULT SYSDATE, 
	ORIGINALFILE VARCHAR(200),
	SAVEDFILE VARCHAR(50),
	HITCOUNT NUMBER DEFAULT 0, 
	REPLYTEXT VARCHAR(2000),
	REPDATE DATE 
);

